### ISSUE TITLE
is there an option to only use file name as template name

### ISSUE THREAD

**Issue by xajhqffl** [vadimi/AngularTemplates.Compile#1]
I only use the file name as template name without the path parameters.

like the template file is in "~/script/angular-app/map/templates/partial.html",
I only need 
$templateCache.put('partial.html', "template1");

is there a way to do this?

Thanks!

**Comment by xajhqffl** [comment]
sorry. it seems like I can use the WorkingDir parameter.

**Comment by vadimi** [comment]
@Fangmingdu yes, `WorkingDir` is the way to go.
