### ISSUE TITLE
remove line breaks in template

### ISSUE THREAD

**Issue by xajhqffl** [vadimi/AngularTemplates.Compile#2]
Can you add the code to remove line breaks? It will make the bundle smaller.

.Replace("\r\n", "");

Thanks!

PS. Maybe also remove empty spaces. This will make it look much nicer! :)

**Comment by vadimi** [comment]
Unfortunately it's not that simple. For example such tags as `pre` or `textarea` should preserve white spaces.

**Comment by vadimi** [comment]
New package with that functionality has been released
