### ISSUE TITLE
How to ignore BundleTable.EnableOptimizations

### ISSUE THREAD

**Issue by sergii-golik** [vadimi/AngularTemplates.Compile#4]
Could you add ability to have templates optimizations turned on if BundleTable.EnableOptimizations = false ?

**Comment by vadimi** [comment]
I'll look into it.

**Comment by vadimi** [comment]
https://github.com/vadimi/AngularTemplates.Compile/commit/fa22e2846fde76bd45c7c62b790fd4772cf1d4b7 should cover that issue. Will release new version of the NuGet package soon.

**Comment by vadimi** [comment]
Here you go: [https://www.nuget.org/packages/AngularTemplates.Compile/1.2.1](https://www.nuget.org/packages/AngularTemplates.Compile/1.2.1)
